apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
  annotations:
    # Specify the ARN of your ACM certificate (REPLACE WITH YOUR CERTIFICATE ARN)
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:<REGION>:<AWS_ACCOUNT_ID>:certificate/<CERTIFICATE_ID>"
    # Specify which ports should use SSL
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    # Specify the SSL policy
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    # Specify the backend protocol
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    # Enable cross-zone load balancing
    service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
    # Set the load balancer type to be managed by AWS Load Balancer Controller
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # Set the target type to instance
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    # Set the scheme to internet-facing
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # Add DNS record annotation for ExternalDNS (REPLACE WITH YOUR DOMAIN)
    external-dns.alpha.kubernetes.io/hostname: "<YOUR_DOMAIN>"
spec:
  type: LoadBalancer
  ports:
    - name: "5678"
      port: 5678
      targetPort: 5678
      protocol: TCP
    - name: "https"
      port: 443
      targetPort: 5678
      protocol: TCP

  selector:
    service: n8n
